blgf2wrdprs/urls.py
from django.conf.urls import patterns, url

from blgf2wrdprs import views
from blgf2wrdprs.views import  contact
from blgf2wrdprs.views import thanks

urlpatterns = patterns('',
    url(r'^$',  contact),
    url(r'^thanks$', thanks)
)

blgf2wrdprsSite/urls.py
from django.conf.urls import patterns, include, url
import settings

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    url(r'', include('blgf2wrdprs.urls')),
(
        r'^static/(?P<path>.*)$',
            'django.views.static.serve',
        {'document_root': settings.STATIC_ROOT}
        )
)

blgf2wrdprs/models.py
from django.db import models

# Create your models here.

blgf2wrdprs/forms.py
from django import forms

class ContactForm(forms.Form):
    website = forms.CharField(max_length=100)
    email = forms.EmailField()

  

blgf2wrdprs/views.py
# -*- coding: UTF-8 -*-
 
from django.shortcuts import render
from django.http import HttpResponseRedirect
from blgf2wrdprs.forms import ContactForm
from blgf2wrdprs.exporter.exportBlogfa27  import *
from blgf2wrdprs.exporter.mailer import *
import zipfile
import datetime


def compressFile(name, siteName):
   zippedFile = zipfile.ZipFile(name + ".zip", "w")
   zippedFile.write(name + ".xml", siteName + ".xml")
   zippedFile.close()

def logUsage(siteName, email):
   with open("/tmp/httpd/usage.txt", "a") as myfile:
      myfile.write(str(datetime.datetime.now()) + ' : ' + siteName + ' : ' + email+"\n")  
 
def contact(request):
    if request.method == 'POST': # If the form has been submitted...
        form = ContactForm(request.POST) # A form bound to the POST data
        if form.is_valid(): # All validation rules pass
            email =  form.cleaned_data["email"]
            siteName = form.cleaned_data["website"]
            fileName = "/tmp/" + siteName
            try:
               logUsage(siteName, email)
               extractSite(siteName, fileName)
            except (urllib2.HTTPError, UnicodeEncodeError):
               print "Error site cannot be read"   
               return render (request, 'error.html', { 'errorMessage': u'وبلاگ %s.blogfa.com یافت نشد.' % siteName})
            
            compressFile(fileName, siteName)
            sendEmail(email,   fileName, siteName )
            # Process the data in form.cleaned_data
            # ...
            return HttpResponseRedirect('/thanks') # Redirect after POST
    else:
        form = ContactForm() # An unbound form
    return render(request, 'contact.html', {
        'form': form,
    })


def thanks(request):
    return render(request, 'thanks.html')

blgf2wrdprsSite/templates/contact.html
<html xmlns="http://www.w3.org/1999/xhtml" debug="true" DIR="RTL">

	<head>
	   <title>انتقال وبلاگ از بلاگفا به وردپرس</title>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-51093029-1', 'saeidmirzaei.com');
  ga('send', 'pageview');

</script>
	</head>
	<style>
	   .header {
			  background-color:#3388CC;
			  background-position:initial initial;
			  background-repeat:initial initial;
			  height:80px;
			  margin:0;
			  padding:0;
			  position:relative;
			  
			  
			  color:white;
			  font-family:Arial;
			  font-size:18pt;
			  font-weight:bold;
			  text-align:center;
			  padding-top:40px;
			  position:relative;
			   margin:0;
			   text-align:center;
         }
      .error {
          color:red;
          vertical-align:middle;
         
       }
         
       
	</style>
	
	<body> 
	   <div class="header"> انتقال  وبلاگ از بلاگفا به وردپرس
	   </div>
	     
		<form action="/" method="post">{% csrf_token %}
			    <div class="fieldWrapper">

			<table>
                                <tr></tr>
				<tr>
			  		<td align="left">
			        {{ form.website.errors }}
			        <label for="id_website">نام وبلاگ در بلاگفا:</label>
			        {{ form.website }}
			  		</td>
			  		<td align="right" class="error">
			  		    
			       	{{ form.non_field_errors }}
			 	 	</td>
			 	</tr>
			 	<tr>
			  		<td align="left">
			        <label for="id_email">پست  الکترونیکی:</label>
			        {{ form.email }}
			  		</td>
			 		<td align="right" class="error"> 
			 
			        {{ form.email.errors }}
			 		</td>
			 	</tr>
			    <tr>
			  		<td align="left">
			    		<p><input type="submit" value="تبدیل" /></p>
			    	</td>
			    </tr>
		    </table>
		    </div>
          <div class="header" style="height:30px;padding-top:5px;text-align:right;">
          راهنما
          </div>
          <br>
          <img src="/static/blogfa_setting2.png" alt="some_text"  style="float:left">
          <div>
                لطفا ابتدا تنظیمات زیر را در بلاگفا انجام دهید.	
          <ul>
    
            
            <li>
          	در سایت بلاگفا لاگین کنید.
          	</li>
          	<li>
          	از منوی سمت راست گزینه «تنظیمات و دیگر امکانات» را انتخاب کنید.
          	</li>
          	<li>
          	در قسمت «قالب وبلاگ و کدهای بکار گرفته شده در وبلاگ» گزینه «انتخاب قالب برای وبلاگ» را انتخاب کنید.
          	</li>
          	<li>          	 
          	گزینه «آبی ساده» را انتخاب کنید.
          	</li>
          	<li>
          	به منوی قبل («تنظیمات و دیگر امکانات») باز گردید.
          	</li>
          	<li>
          	قسمت «تنظیمات کلی وبلاگ (عنوان وبلاگ، نام نویسنده، منطقه زمانی یا نحوه نمایش تاریخ مطالب یا آرشیو)» را انتخاب کنید.
          	</li>
          	<li>          	 
          	تنظیمات زیر را اعمال کنید
          	</li>
          	<li>
          		نحوه نمایش تاریخ پستها: نمایش تاریخ به صورت میلادی مانند 2004/5/20
          	</li>
          	<li>          		 
          		نحوه نمایش زمان پستها: نمایش ساعت و دقیقه - مانند 14:30
          	</li>
          	<li>          		 
          		نحوه نمایش تاریخ آرشیو: نمایش نام ماه یا هفته و سال مانند خرداد ۱۳۸۲ یا هفته اول خرداد ۱۳۸۲
          	</li>
          	<li>          		
          		نحوه آدرس‌دهی صفحات: به شیوه قدیمی (مانند post-1.aspx)
          	</li>
          	</div>
          	<div>
          		<br>
یعد از انجام تغییرات فوق، در فرم بالا، در فیلد «نام وبلاگ در بلاگفا» <b>قسمت اول</b> وبلاگ خود را وارد کنید. 
</br>
به عنوان مثال، برای وبلاگ http://saeedmirzai.blogfa.com/ کافی است تنها saeedmirzai را وارد کنید.
</br>
در قسمت پست الکترونیکی نیز پست الکترونیکی مورد نظر خود را وارد کنید.
</br>
با فشردن دکمه «تبدیل» عمل تبدیل صورت خواهد گرفت و فایل حاصل به صورت فشرده شده به آدرس داده شده ایمیل خواهد شد.
          	          		</br>
          	          		</br>
پستها، کامنتها، برچسبها و دسته‌بندی‌ها، همه منتقل خواهند شد. 
</br>

در صورت وجود مشکل، با ذکر توضیحات لازم، ترجیحا به زبان فارسی، به آدرس  blogfa2wordpress at saeidmirzaei.com ایمیل بزنید.
</br>
از شنیدن تجربیات مثبت شما نیز خوشحال خواهم شد.
          
          </div>
		</form>
	</body>
</html>

blgf2wrdprsSite/templates/error.html
<html xmlns="http://www.w3.org/1999/xhtml" debug="true" DIR="RTL">

	<head>
	   <title>خطا</title>
	</head>
	<style>
	   .header {
			  background-color:#3388CC;
			  background-position:initial initial;
			  background-repeat:initial initial;
			  height:80px;
			  margin:0;
			  padding:0;
			  position:relative;
			  
			  
			  color:white;
			  font-family:Arial;
			  font-size:18pt;
			  font-weight:bold;
			  text-align:center;
			  padding-top:40px;
			  position:relative;
			   margin:0;
			   text-align:center;
         }
      .errorMessage {
			  color:blue;
			  font-family:Arial;
			  font-size:28pt;
			  font-weight:bold;
			  text-align:center;
			  padding-top:40px;
          vertical-align:middle;
         
       }
         
       
	</style>
	
	<body> 
	   <div class="header"> خطا
	   </div>
	   <div class="errorMessage"> {{errorMessage}}</div>
	     
		
	</body>
</html>

blgf2wrdprsSite/templates/thanks.html
Thanks